org: chittaworn
app: user-service-app
service: user-service

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  stage: ${opt:stage, 'dev'}
  environment:
    DB_HOST: ${env:DB_HOST, 'localhost'}
    DB_USER: ${env:DB_USER, 'root'}
    DB_PASSWORD: ${env:DB_PASSWORD, ''}
    DB_NAME: ${env:DB_NAME, 'serverless_offline'}

plugins:
  - serverless-offline

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true

functions:
  createUser:
    handler: handler.createUser
    events:
      - httpApi:
          path: /${sls:stage}/users
          method: post
  listUsers:
    handler: handler.listUsers
    events:
      - httpApi:
          path: /${sls:stage}/users
          method: get
  getUser:
    handler: handler.getUser
    events:
      - httpApi:
          path: /${sls:stage}/users/{id}
          method: get
  findByEmail:
    handler: handler.findByEmail
    events:
      - httpApi:
          path: /${sls:stage}/users/search
          method: get
  updateUser:
    handler: handler.updateUser
    events:
      - httpApi:
          path: /${sls:stage}/users/{id}
          method: put
  deleteUser:
    handler: handler.deleteUser
    events:
      - httpApi:
          path: /${sls:stage}/users/{id}
          method: delete
